name: hello_workflow
on: [push]
jobs:
  print-hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Hello world using echo
        run: echo "$(<hello.txt)"
      - name: Hello world using cat
        run: cat hello.txt
  show-secret-phrase:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: abystoma/test
          ref: CombinedPhrase
      - name: Create file "hello.txt" with the word Hello
        run: touch hello.txt && echo "Hello" > hello.txt
      - name: Show me the answer
        run: cat hello.txt from.txt
